#!/bin/bash

echo "Disabling rxPDO assignment: "
sudo ethercat download -t uint8 0x1C12 0 0

echo "Shutting down all rxPDO mappings:"
sudo ethercat download -t uint8 0x1600 0 0
sudo ethercat download -t uint8 0x1601 0 0
sudo ethercat download -t uint8 0x1602 0 0
sudo ethercat download -t uint8 0x1603 0 0

echo "Changing 0x1600 mapping to Control Word"
sudo ethercat download -t uint32 0x1600 1 0x60400010
sudo ethercat download -t uint8 0x1600 0 1

echo "Changing rxPDO assignment to 0x1600: "
sudo ethercat download -t uint16 0x1C12 1 0x1600

echo "Enabling rxPDO: "
sudo ethercat download -t uint8 0x1C12 0 1



echo "Disabling txPDO: "
sudo ethercat download -t uint8 0x1C13 0 0

echo "Shutting down all rxPDO mappings:"
sudo ethercat download -t uint8 0x1A00 0 0
sudo ethercat download -t uint8 0x1A01 0 0
sudo ethercat download -t uint8 0x1A02 0 0
sudo ethercat download -t uint8 0x1A03 0 0

echo "Changing 0x1A00/0x1A01 mapping to Status Words"
sudo ethercat download -t uint32 0x1A00 1 0x60410010
sudo ethercat download -t uint32 0x1A00 1 0x60630020
sudo ethercat download -t uint8 0x1A00 0 1

echo "Changing txPDO assignment to 0x1B01: "
sudo ethercat download -t uint16 0x1C13 1 0x1B01

echo "Enabling txPDO: "
sudo ethercat download -t uint8 0x1C13 0 1

echo "Setting for Cyclic Pos Mode"
sudo ethercat download -t uint8 0x6060 0 8